### ISSUE TITLE
Feature Request: Add littlefs for ESP32

### ISSUE THREAD

**Issue by Jason2866** [maxgerhardt/pio-esp32-esp8266-filesystem-downloader#1] opened 2021-01-13 13:12 UTC
Great addon! It would be great if you add littlefs for ESP32. We use it for ESP32 already. See [Tasmota](https://github.com/arendst/Tasmota)

**Comment by maxgerhardt** [comment] 2021-01-13 14:47
Closing as accidental duplicate of #2? ^^

**Closed as completed by maxgerhardt** 2021-01-13 14:47 UTC

**Comment by Jason2866** [comment] 2021-01-13 15:06
Sorry, i had problems with my inet connection.
